export async function onRequestPost(context) {
  try {
    const data = await context.request.json();

    const email = (data.email || "").trim();
    const report = data.report || "";
    const scannedUrl = data.scanned_url || "";
    const ownerEmail = context.env.OWNER_EMAIL || "contact@5thelement.ai";
    const fromEmail = context.env.FROM_EMAIL || "AI LENS <onboarding@resend.dev>";
    const resendKey = context.env.RESEND_API_KEY;

    if (!resendKey) {
      return Response.json({ ok:false, error:"Missing RESEND_API_KEY environment variable." }, { status:500 });
    }
    if (!email) {
      return Response.json({ ok:false, error:"Client email is required." }, { status:400 });
    }
    if (!report) {
      return Response.json({ ok:false, error:"Report content is missing." }, { status:400 });
    }

    const subject = `AI LENS™ report for ${scannedUrl || "your website"}`;

    const text = `${report}

---
This free AI LENS™ scan was generated by 1clic-ia.eu.
Contact: ${ownerEmail}
`;

    const html = `
      <div style="font-family:Arial,sans-serif;line-height:1.6;color:#111">
        <h2>AI LENS™ Report</h2>
        <p><b>Website:</b> ${escapeHtml(scannedUrl)}</p>
        <pre style="white-space:pre-wrap;background:#f6f6f6;border:1px solid #ddd;padding:16px;border-radius:8px">${escapeHtml(report)}</pre>
        <p>This free AI LENS™ scan was generated by <b>1clic-ia.eu</b>.</p>
        <p>Contact: ${escapeHtml(ownerEmail)}</p>
      </div>
    `;

    const payload = {
      from: fromEmail,
      to: [email],
      bcc: [ownerEmail],
      subject,
      text,
      html
    };

    const res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${resendKey}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify(payload)
    });

    const out = await res.json();

    if (!res.ok) {
      return Response.json({ ok:false, error: out.message || JSON.stringify(out) }, { status:500 });
    }

    return Response.json({ ok:true, id: out.id || null });
  } catch (err) {
    return Response.json({ ok:false, error: err.message }, { status:500 });
  }
}

export async function onRequestGet() {
  return Response.json({ ok:true, endpoint:"AI LENS automatic email endpoint is live." });
}

function escapeHtml(s) {
  return String(s || "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}
